<div id="board">
    <h3>Official Time: <?php echo $this->currentTime; ?></h3>
    <h5>Block Countdown: <?php echo $this->countdown; ?></h5>
    <table>
        <thead>
        <tr>
            <td colspan="2">BLOCK <?php echo $this->blockNumber; ?> ~ <?php echo $this->startTime; ?> - <?php echo $this->endTime; ?></td>
            <td>Value</td>
            <td>Bid</td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->items as $item) {
            $minBid = round($item->fairRetailPrice * $this->getMinBidPercent());
            $minBid -= ($minBid %5);
            $openingBid = $minBid - 5;

            $bidClass = '';
            if ($item->bid >= $item->fairRetailPrice) {
                $bidClass = 'bell-ringer';
            }
            ?>
            <tr>
                <td><?php echo htmlentities($item->controlNumber); ?></td>
                <td class="fill"><?php echo htmlentities($item->name); ?></td>
                <td><?php echo htmlentities(floor($item->fairRetailPrice)); ?></td>
                <td class="<?php echo $bidClass; ?>"><?php echo ($item->bid > 0?floor($item->bid):$openingBid); ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>