<div class="col-lg-6">
    <h3>Official Broadcast</h3>
    <p>Please note the the stream will always lag behind the real time. Please use the official time as reference
        for when blocks will close.</p>

    <div class="embed-responsive embed-responsive-4by3">
        <iframe
                src="//player.streammonkey.com/iframe/hpjsjbrw"
                frameborder="no"
                scrolling="no"
                allow="autoplay" allowfullscreen webkitAllowFullScreen mozAllowFullscreen>
        </iframe>
    </div>
</div>
<div class="col-lg-6 ml-auto" id="bid-board">
    <div id="board">
        <h3>Official Time: <?php echo $this->currentTime; ?></h3>
        <?php if (count($this->items) == 0){?>
            <p>Watch the live broadcast on Saturday November 23rd 2019 from 10am to midnight.</p>
        <?php } else { ?>
        <h5>Block Countdown: <?php echo $this->countdown; ?></h5>
        <table class="table">
            <thead>
            <tr>
                <td colspan="2">BLOCK <?php echo $this->blockNumber; ?> ~ <?php echo $this->startTime; ?> - <?php echo $this->endTime; ?></td>
                <td>Value</td>
                <td>Bid</td>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->items as $item) {
                $minBid = round($item->fairRetailPrice * $this->getMinBidPercent());
                $minBid -= ($minBid %5);
                $openingBid = $minBid - 5;

                $bidClass = '';
                if ($item->bid >= $item->fairRetailPrice) {
                    $bidClass = 'bell-ringer';
                }
                ?>
                <tr>
                    <td><?php echo htmlentities($item->controlNumber); ?></td>
                    <td><?php echo htmlentities($item->name); ?></td>
                    <td class="text-right">$<?php echo htmlentities(floor($item->fairRetailPrice)); ?></td>
                    <td class="text-right <?php echo $bidClass; ?>">$<?php echo ($item->bid > 0?floor($item->bid):$openingBid); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <?php } ?>
        <h4>BID LINE: 416-406-6187</h4>
        <h4>INFO LINE: 416-508-8382</h4>
    </div>
</div>