<div class="col-lg-6">
    <h3>Official Broadcast</h3>
    <p>Please note the the stream will always lag behind the real time. Please use the official time as reference
        for when blocks will close.</p>

    <div class="embed-responsive embed-responsive-4by3">
            <iframe
                    src="//player.streammonkey.com/iframe/hpjsjbrw"
                    frameborder="0"
                     allow="autoplay" allowfullscreen webkitAllowFullScreen mozAllowFullscreen>
            </iframe>
    </div>
    </div>
</div>
<div class="col-lg-6" id="bid-board">
    <div id="board">
        <h3>Official Time: <?php echo $this->currentTime; ?></h3>
        <h5>Block Countdown: <?php echo $this->countdown; ?></h5>
        <table class="table">
            <thead>
            <tr>
                <td colspan="2">BLOCK <?php echo $this->blockNumber; ?> ~ <?php echo $this->startTime; ?> - <?php echo $this->endTime; ?></td>
                <td>Value</td>
                <td>Bid</td>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->items as $item) {
                $minBid = round($item->fairRetailPrice * $this->getMinBidPercent());
                $minBid -= ($minBid %5);
                $openingBid = $minBid - 5;

                $bidClass = '';
                if ($item->bid >= $item->fairRetailPrice) {
                    $bidClass = 'bell-ringer';
                }
                ?>
                <tr>
                    <td><?php echo htmlentities($item->controlNumber); ?></td>
                    <td><?php echo htmlentities($item->name); ?></td>
                    <td class="text-right">$<?php echo htmlentities(floor($item->fairRetailPrice)); ?></td>
                    <td class="text-right <?php echo $bidClass; ?>">$<?php echo ($item->bid > 0?floor($item->bid):$openingBid); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>