<div class="modal-header">
    <h5 class="modal-title" id="itemdetailstitle"><?php echo $this->item->itemName; ?></h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <h5>Item #<?php echo $this->item->controlNumber; ?></h5>
                <h5>Block <?php echo $this->item->blockNumber; ?></h5>
                <h5>Time: <?php echo date("g:ia", strtotime($this->item->blockDate . " " . $this->item->blockTime)); ?></h5>
                <h4>Value $<?php echo $this->item->fairRetailPrice; ?></h4>
            </div>
            <div class="col-md-8">
                <p><?php echo $this->item->itemDescription; ?></p>

                <h5>Donor</h5>
                <?php echo $this->item->donor_companyName==''?'':$this->item->donor_companyName . '<br />'; ?>
                <?php echo $this->item->donor_lastName==''?'':$this->item->donor_firstName . ' ' . $this->item->donor_lastName . '<br />'; ?>
            </div>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>