
    <script type="text/javascript" src="/js/jquery.progressbar.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Task');
        data.addColumn('number', 'Hours per Day');
        data.addRows(<?php echo count($this->leaderBoard); ?>);
        <?php $rownum = 0; ?>
        <?php $total_items = 0;?>
    	<?php foreach ($this->leaderBoard as $row ) { ?>
        data.setValue(<?php echo $rownum;?>, 0, '<?php echo str_replace('Rotary Club of', 'RC', $row->name); ?>');
        data.setValue(<?php echo $rownum;?>, 1, <?php echo $row->itemCount; ?>);
    	<?php $rownum++; ?>
    	<?php $total_items += $row->itemCount; ?>
    	<?php } ?>
        var chart = new google.visualization.PieChart(document.getElementById('chart_div'));
        chart.draw(data, {width: 450, height: 300, title: 'Items by Club', backgroundColor: '#EEE', is3D: true, legend: 'top', legendTextStyle: {color: '#000', fontName: 'Arial', fontSize: '9'}, titleTextStyle: {color: '#000', fontName: 'Arial', fontSize: '16'}, chartArea: {left:20,top:40,width:"100%",height:"95%"}});
      }

	  jQuery(document).ready(function() {
      	jQuery("#progress_bar").progressBar({width		: 120,
      		height			: 12,
      		callback		: null,
      		boxImage		: '/images/progressbar.gif',
      		barImage		: {
      			0:  '/images/progressbg_red.gif',
      			50: '/images/progressbg_orange.gif',
      			75: '/images/progressbg_green.gif'
      		}
      	});
	  });
    </script>
    
<div id="home_shortcuts">
    <h1>Welcome to the Toronto Online Auction System.</h1>
    <p>You are logged into the system used by the Toronto Rotary Online Auction.
    When you're done using the system, please remember to <a href="/index/index/logout">LOGOUT</a>. For your convenience, there is
    a logout button at the top right of the page.</p>

    <h3>SHORTCUTS</h3>
    <ul>
        <li><a href="/items/index/newitem">ENTER AN ITEM</a></li>
        <li><a href="/items/index/itemlist">ITEM LIST</a></li>
    </ul>

    <h3>WAREHOUSE</h3>
    <p>The warehouse is located at <a href="https://goo.gl/maps/JW8kWnRa9rC2" target="map">40 Carabob Court in Scarborough</a>, near Birchmount &amp; Sheppard East.</p>
    <p>To arrange a delivery of items, you can contact Nicole at
        <a href="mailtp:nicole.patterson@eastyorkrotary.org">nicole.patterson@eastyorkrotary.org</a> or
        <a href="tel:+16477866465">647-786-6465</a>.</p>

</div>
<?php 
$total_lead = 0;
$total_rota = 0;
?>
<div id="home_leaderboard">
	<div id="item_goal">
		<label>GOAL:</label>
		<div id="goal_progress"><?php echo $total_items; ?> of <?php echo $this->goal; ?> items.</div>
		<div id="progress_bar"><?php echo round($total_items / $this->goal * 100); ?></div>
	</div>
	<div id="chart_div"></div>
	<!-- 
	<table>
		<thead>
			<tr>
				<td colspan="2">Item Leaderboard</td>
			</tr>
			<tr>
				<td>Club/Organization</td>
				<td>Items</td>
				<td>Value</td>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->leaderBoard as $row ) { ?>
		<?php $total_lead += $row->itemCount; ?>
			<tr>
				<td><?php echo $row->name; ?></td>
				<td><?php echo $row->itemCount; ?></td>
				<td><?php echo $row->value; ?></td>
			</tr>
	<?php } ?>
		</tbody>
		<tfoot>
			<tr>
				<td>Total Items:</td>
				<td><?php echo $total_lead; ?></td>
			</tr>
		</tfoot>
	</table>
	 -->
	<table>
		<thead>
			<tr>
				<td colspan="3">Top 10 Rotarians</td>
			</tr>
			<tr>
				<td>Rotarian</td>
				<td>Items</td>
				<td>Value</td>
			</tr>
		</thead>
		<tbody>
	<?php foreach ($this->rotarians as $rotarian ) { ?>
		<?php $total_rota += $rotarian->itemCount; ?>
			<tr>
				<td><?php echo $rotarian->firstName; ?> <?php echo $rotarian->lastName; ?></td>
				<td class="center"><?php echo $rotarian->itemCount; ?></td>
				<td class="right">$<?php echo $rotarian->value; ?></td>
			</tr>
	<?php } ?>
		</tbody>
	</table>
</div>