<?php if ($this->found == true) {?>
<p>Please enter a new password:</p>

<form action="/index/index/resetpasswordconfirmprocess" method="post">
	<?php echo $this->formHidden('userId', $this->userId); ?>
	<?php echo $this->formHidden('key', $this->key); ?>
	<dl>
		<dt><label for="">New Password:</label></dt>
		<dd><?php echo $this->formPassword('npass'); ?></dd>
		<dt><label for="">Confirm Password:</label></dt>
		<dd><?php echo $this->formPassword('cpass'); ?></dd>
	</dl>
	<?php echo $this->formSubmit('Change Password', 'Change Password'); ?>
</form>
<?php } else { ?>
<p>There is a problem with the reset.</p>
<?php } ?>