<?php if ($this->found == true) {?>
	<?php if ($this->senderror == true) {?>
<h3>Whoops!</h3>
<p>The reset email could not be sent for some reason. Please <a href="mailto:darryl@eastyorkrotary.org">email Darryl</a>.</p>
	<?php } else {?>
<h3>Success!</h3>
<p>Please check your email for instructions on resetting your password.</p>
<?php } } else { ?>
<h3>Whoops!</h3>
<p>The email address wasn't found.</p>
<?php } ?>
