<div id="gettoken">
	<p>You've requested to log in to the Metro Toronto Rotary Auction system. To complete your login, simply click on the
	link below and then enter your username and password. This request will expire at <?php echo $this->layout()->expiry; ?></p>
	<p><a href="https://system.metrotorontorotaryauction.com/index/index/login/t/<?php echo $this->layout()->token; ?>">COMPLETE LOGIN</a></p>
</div>