<div id="addItemDeets">
	<table id="itemPrintHeader" width="95%" cellpadding="5">
		<tr>
			<td width="100"><img src="http://system.metrotorontorotaryauction.com/images/ri_emblem_c_100x100.png" width="100" height="100" /></td>
			<td align="center" style="font-size: 18pt; font-weight: bold">
				Metro Toronto Rotary Auction
			</td>
			<td width="130" align="center">
				CONTROL NUMBER
				<div id="controlNumber" style="font-size:20pt;font-weight:bold;padding:25px 0 0 0;">
					<?php echo $this->layout()->item->controlSource . $this->layout()->item->controlNumber; ?>
				</div>
			</td>
		</tr>
	</table>
	<hr />
	<table width="95%" cellpadding="5">
		<tbody>
			<tr>
				<td valign="top" width="150">Company Name:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_companyName; ?></td>
			</tr>
			<tr>
				<td valign="top">Contact:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_firstName; ?> <?php echo $this->layout()->item->donor_lastName; ?></td>
			</tr>
			<tr>
				<td valign="top">Address 1:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_address1; ?></td>
			</tr>
			<tr>
				<td valign="top">Address 2:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_address2; ?></td>
			</tr>
			<tr>
				<td valign="top">City, Province:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_city; ?>, <?php echo $this->layout()->item->donor_province; ?></td>
			</tr>
			<tr>
				<td valign="top">Phone Number:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_phone; ?></td>
			</tr>
			<tr>
				<td valign="top">Email Address:</td>
				<td valign="top"><?php echo $this->layout()->item->donor_email; ?></td>
			</tr>
		</tbody>
	</table>
	<hr />
	<table width="95%" cellpadding="5">
		<tbody>
			<tr>
				<td width="150" valign="top">Item Name:</td>
				<td valign="top"><?php echo $this->layout()->item->itemName; ?></td>
			</tr>
			<tr>
				<td valign="top">Fair Retail Value:</td>
				<td valign="top"><?php echo $this->layout()->item->fairRetailPrice; ?></td>
			</tr>
			<tr>
				<td valign="top">Item Description:</td>
				<td valign="top"><?php echo $this->layout()->item->itemDescription; ?></td>
			</tr>
			<tr>
				<td valign="top">Tax Receipt:</td>
				<td valign="top"><?php echo $this->layout()->item->taxReceipt; ?></td>
			</tr>
		</tbody>
	</table>
</div>