<div id="confirmResetDeets">
	<table id="confirmResetHeader" width="95%" cellpadding="5">
		<tr>
			<td width="100"><img src="http://system.metrotorontorotaryauction.com/images/ri_emblem_c_100x100.png" width="100" height="100" /></td>
			<td align="center" style="font-size: 18pt; font-weight: bold">
				Metro Toronto Rotary Auction
			</td>
			<td width="130" align="center">
				RESET PASSWORD
			</td>
		</tr>
	</table>
	<hr />
	<p>You have received this email because you have requested to reset your password for the MTRA System.</p>
	<p>To reset your password, <a href="http://system.metrotorontorotaryauction.com/index/index/resetpasswordconfirm/id/<?php echo $this->layout()->userId; ?>/key/<?php echo $this->layout()->key; ?>">CLICK HERE</a>.</p>
</div>