<h2>Welcome to the Toronto Online Auction System!</h2>

<p>You have received this email because you have been identified as someone who will be doing item entry on behalf
of their club or organization. This email contains important information that will assist you with item entry this year.</p>

<h3>Your Login Info</h3>

<p>Every individual has their own login for the system. You must be able to check your email when logging in, as
you must request a login in order to access the system. If this is your first time accessing the Auction System, you
will need to request a password reset. The attached procedure document describes how this is accomplished. There is
also a video you can view that walks you through the process. Your username for the Auction System is in the format of
your first name, a "dot", and then your last name. For example, my name is Darryl Patterson, therefore my username is
darryl.patterson. Although all club members are in the database, only those identified as people doing item entry
will be able to login.</p>

<p>The system can be found at
<a href="http://system.metrotorontorotaryauction.com/">system.metrotorontorotaryauction.com</a>.</p>

<h3>Training Videos</h3>

<p>We have produced three videos that will walk you through the procedure for resetting your password, logging
into the system, and entering items. They have been posted to YouTube so that they may be viewed at any time.
The videos may be found here:</p>

<div>Password Reset:<br />
http://www.youtube.com/watch?v=4L1tzs9D3yU
</div>

<div>
Login:<br />
http://www.youtube.com/watch?v=CwuOCpWAgRQ
</div>

<div>
Item Entry:<br />
http://www.youtube.com/watch?v=lguF56JYnyE
</div>

<h3>Procedures Document</h3>

<p>We have also produced a document that has a step-by-step description of the procedures to get you started with item entry
The document is attached.</p>

<h3>Warehouse Check-In Procedure</h3>

<p>We are working in a new check-in procedure document for the warehouse. We'll send it to you when it's ready.</p>

<p>If you have any questions regarding item entry, please email me at darryl@eastyorkrotary.org or you can try calling me
at (416) 786-6116. Email works best for me as I often am not able to answer a phone - I tend to be in meetings a lot. :)</p>

<p>The MTRA board thanks you all for contributing with item entry.</p>
