<h2>Thanks for Bidding!</h2>
<p>On behalf of the Metro Toronto Rotary Auction, we thank for supporting our efforts this year.</p>

<h3>Item Pick-Up Procedure</h3>

<p>Make your way to the East York Civic Centre (see below). You may enter the doors on Coxwell or O'Connor.
Once in the Civic Centre, go to the payment desk. You will be asked for the phone number you used when you
were called back after winning an item. The kind folks behind the desk will print you an invoice and they
will settle payment (we take cash, debit, visa &amp; mastercard). Once you've paid, you'll be directed to
the item pick-up area. Present your invoice (stamped PAID) to the kind volunteers there, and they will collect
your items for you.</p>

<h3>Item Pick-Up Location</h3>

<p>Your item(s) may be picked up at the East York Civic Centre. The address is:<br />
850 Coxwell Avenue<br />
Toronto, ON M4C 5R1<br />
<a href="http://maps.google.com/maps?q=East+York+Civic+Centre,+Toronto,+Ontario,+Canada&hl=en&sll=37.0625,-95.677068&sspn=50.644639,92.460937&vpsrc=0&hnear=East+York+Civic+Centre,+Toronto,+Toronto+Division,+Ontario+M4C+5R1,+Canada&t=m&z=16">GOOGLE MAP</a></p>

<h3>Item Pick-Up Hours</h3>

<p>Items may be picked up at the following hours:</p>
<ul>
	<li>Saturday, Nov 26th from noon to 11pm</li>
	<li>Sunday, Nov 27th from 10am to 2pm</li>
</ul>

<h3>Parking &amp; Transit</h3>

<p>There is ample parking available on the streets around the civic centre. There is also paid parking in the lot off O'Connor.</p>
<p>If you're arriving via TTC, please take either the 70 O'Connor bus (from Coxwell or Warden subway stations) or the
62 Mortimer bus (from Broadview or Main subway stations).</p>

<h3>Contact Information</h3>

<p>If you have any questions, please call our info line or send us an email.</p>
<p>Phone: (416) 406-4342<br />
Email: <a href="mailto:info@metrotorontorotaryauction.com">info@metrotorontorotaryauction.com</a></p>

<h3>Thanks for your support!</h3>
