<h1>Editing eBay details for item <em><?php echo $this->item->name; ?></em></h1>


<div id="itemInfo">
    <form action="/items/index/ebayprocess" method="post">
        <?php echo $this->formHidden('itemEbayId', $this->ebay->itemEbayId); ?>
        <?php echo $this->formHidden('itemId', $this->item->itemId); ?>
        <dl>
            <dt><label for="upc">UPC</label></dt>
            <dd><?php echo $this->formText('upc', $this->ebay->upc, array('id' => 'upc', 'size' => 15, 'maxlength' => 12)); ?></dd>
            <dt><label for="weight">Weight (kg)</label></dt>
            <dd><?php echo $this->formText('weight', $this->ebay->weight, array('id' => 'weight', 'size' => 5, 'maxlength' => 6)); ?></dd>
            <dt><label for="boxSize">Box Size</label></dt>
            <dd><?php echo $this->formText('boxSize', $this->ebay->boxSize, array('id' => 'boxSize', 'size' => 5, 'maxlength' => 3)); ?></dd>
            <dt><label for="width">Width (cm)</label></dt>
            <dd><?php echo $this->formText('width', $this->ebay->width, array('id' => 'width', 'size' => 5, 'maxlength' => 3)); ?></dd>
            <dt><label for="height">Height (cm)</label></dt>
            <dd><?php echo $this->formText('height', $this->ebay->height, array('id' => 'height', 'size' => 5, 'maxlength' => 3)); ?></dd>
            <dt><label for="length">Length (cm)</label></dt>
            <dd><?php echo $this->formText('length', $this->ebay->length, array('id' => 'length', 'size' => 5, 'maxlength' => 3)); ?></dd>
            <dt><label for="minimumBid">Minimum Bid</label></dt>
            <dd><?php echo $this->formText('minimumBid', $this->ebay->minimumBid, array('id' => 'minimumBid', 'size' => 10, 'maxlength' => 8)); ?></dd>
            <dt><label for="winningBid">Winning Bid</label></dt>
            <dd><?php echo $this->formText('winningBid', $this->ebay->winningBid, array('id' => 'winningBid', 'size' => 10, 'maxlength' => 8)); ?></dd>

        <?php echo $this->formSubmit('', 'Save Changes'); ?>
        <?php echo $this->formButton('', 'Cancel', array('onclick' => 'window.location="/items/index/itemlist"')); ?>
    </form>
</div>
