<?php if (count($this->items) > 0) { ?>
<div id="customer_info">
	<h3>Customer Information</h3>
	<dl>
		<dt>Phone Number:</dt>
		<dd><?php echo $this->customer->phone; ?></dd>
		<dt>First Name:</dt>
		<dd><?php echo $this->customer->firstName; ?></dd>
		<dt>Last Name:</dt>
		<dd><?php echo $this->customer->lastName; ?></dd>
		<dt>Address:</dt>
		<dd>
			<?php echo $this->customer->address1; ?><br />
			<?php echo $this->customer->city; ?>, <?php echo $this->customer->province; ?> <?php echo $this->customer->postalCode; ?>
		</dd>
		<dt>Email Address:</dt>
		<dd><?php echo $this->customer->email; ?></dd>
	</dl>
</div>
<div id="customer_items">
	<h3>Items they Won</h3>
	<form action="/pickups/index/createinvoice" method="post">
    <?php if ($this->deliver) { ?>
        <input type="hidden" name="deliver" value="y" />
    <?php } ?>
		<?php echo $this->formHidden('phone', $this->customer->phone); ?>
		<table>
			<thead>
				<tr>
					<th>Control Number</th>
					<th>BIN Number</th>
					<th>Block Number</th>
					<th>Item Number</th>
					<th>Pieces</th>
					<th>Item Name</th>
					<th>Item Value</th>
					<th>Winning Bid</th>
					<th>Want?</th>
				</tr>
			</thead>
			<tbody>
		<?php 
			$total = 0;
			foreach ($this->items as $item) {
				$total += $item->bid;
			?>
				<tr>
					<td><?php echo ($item->controlSource . $item->controlNumber);?></td>
					<td><?php echo $item->binNumber; ?></td>
					<td><?php echo $item->blockNumber; ?></td>
					<td><?php echo $item->itemNumber; ?></td>
					<td><?php echo $item->numberOfPieces; ?></td>
					<td><?php echo $item->itemName; ?></td>
					<td><?php echo $item->itemValue; ?></td>
					<td>$<?php echo $item->bid; ?></td>
					<td><?php echo $this->formCheckbox('want[]', $item->bidId, array('checked' => true)); ?></td>
				</tr>
		<?php } ?>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="7">Total:</td>
					<td>$<?php echo $total; ?></td>
					<td>&nbsp;</td>
				</tr>
			</tfoot>
		</table>
		<input type="button" value="Print Runner Sheet" onclick="window.print(); return false;" />
		<input type="submit" value="Create Invoice" />
		<input type="button" value="Cancel" onclick="location='/pickups'" />
	</form>
</div>
<?php } else { ?>
	<p>No items found!</p>
<?php } ?>