
<h1>Operational Exports</h1>
<ul>
	<li><a href="/items/exports/logicalSort">Generate Logical Sort Sheets PDF</a> (<a href="/pdf/logicalSort_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/itemlabels">Generate Item Labels PDF</a> (<a href="/pdf/itemLabels_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>) for Inventory (Avery 6498)</li>
	<li><a href="/items/exports/inventory">Generate Inventory Sheets PDF</a> (<a href="/pdf/inventorySheets_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/blocksheet">Generate Block Sheet PDF</a> (<a href="/pdf/blocksheets_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/itemlist/type/ops">Generate Item List PDF</a> (<a href="/pdf/itemlist_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/itemlist/type/feature">Generate Feature List PDF</a> (<a href="/pdf/featurelist_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/itemlist/type/public">Generate Public List PDF</a> (<a href="/pdf/publiclist_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
	<li><a href="/items/exports/bible">Generate Bible PDF</a> (<a href="/pdf/bible_<?php echo $this->getActiveAuctionDate(1); ?>.pdf">view</a>)</li>
</ul>
