<div id="fbap_canvas_items">
<a href="/facebook">Back to List</a>

<h2><?php echo $this->item->itemName; ?></h2>
<p><?php echo nl2br($this->item->itemDescription); ?></p>
<table border="0" class="item_info">
	<tr>
		<td>Donor:</td>
		<td>
		<?php if ($this->item->anonymous == 'n') { ?>
		    <div>
			    <?php echo ($this->item->donor_companyName==''?'':$this->item->donor_companyName); ?>
			    <?php echo ($this->item->donor_firstName==''?'':'<br />' . $this->item->donor_firstName . ' ' . $this->item->donor_lastName); ?>
			<?php if ($this->item->publishAddress == 'y' && $this->item->donor_companyName != '') { ?>
			    <?php echo ($this->item->donor_address1==''?'':'<br />' . $this->item->donor_address1); ?>
			    <?php echo ($this->item->donor_city==''?'':'<br />' . $this->item->donor_city . ', ' . $this->item->donor_province); ?>
			    <?php echo ($this->item->donor_phone==''?'':'<br />' . $this->formatPhoneNumber($this->item->donor_phone)); ?>
			    <?php echo ($this->item->donor_email==''?'':'<br /><a href="mailto:' . $this->item->donor_email . '">' . $this->item->donor_email . '</a>'); ?>
			    <?php echo ($this->item->donor_website==''?'':'<br /><a href="http://' . $this->item->donor_website . '" target="donorwindow">visit website</a>'); ?>
			<?php } ?>
		    </div>
		<?php } else { ?>
			Anonymous
		<?php } ?>
		</td>
	</tr>
	<tr>
		<td>Up for Auction:</td>
		<td><?php echo (($this->item->blockTime==''||$this->item->blockTime=='00:00:00')?'NA':date("l @ g:ia", strtotime($this->item->blockDate . ' ' . $this->item->blockTime))); ?></td>
	</tr>
	<tr>
		<td>Item Number:</td>
		<td><?php echo (($this->item->controlNumber==''||$this->item->controlNumber=='0')?'NA':$this->item->controlNumber); ?></td>
	</tr>
	<tr>
		<td>Block Number:</td>
		<td><?php echo (($this->item->blockNumber==''||$this->item->blockNumber=='0')?'NA':$this->item->blockNumber); ?></td>
	</tr>
	<tr>
		<td>Retail Value:</td>
		<td><?php echo ($this->item->fairRetailPrice==''?'NA':'$' . $this->item->fairRetailPrice); ?></td>
	</tr>
</table>

	<div class="fb-share-button"
				 data-href="http://apps.facebook.com/rotaryauction/index/view/item/<?php echo $this->item->itemId; ?>"
				 data-layout="button_count">
	</div> <br />
<a href="/facebook">Back to List</a>
</div>
