<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
	<title><?php echo $this->title; ?></title>
	<?php echo $this->ogtags; ?>
		
		<link href='https://fonts.googleapis.com/css?family=Actor' rel='stylesheet' type='text/css' />
		<link href='https://fonts.googleapis.com/css?family=Amaranth:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
		<link href='https://fonts.googleapis.com/css?family=Hammersmith+One' rel='stylesheet' type='text/css' />
		
	<style type="text/css" title="currentStyle"> 
		@import "/datatables/css/demo_page.css";
		@import "/datatables/css/demo_table.css";
	</style> 
	
		<link rel="stylesheet" type="text/css" media="screen, projection, handheld" href="/css/reset.css" />
		<link rel="stylesheet" type="text/css" media="screen, projection, handheld" href="<?php echo $this->getThemePath('css'); ?>facebook.css" />
		
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js"></script>
	<script type="text/javascript" src="/datatables/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript">

	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-69022-6']);
	  _gaq.push(['_setDomainName', 'none']);
	  _gaq.push(['_setAllowLinker', true]);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
</head>
<body id="fb_canvas_body">
<div id="fb-root"></div>
<script type="text/javascript" src="https://connect.facebook.net/en_US/all.js"></script>
<script type="text/javascript">
       FB.init({
         appId  : '134466619926785',
         status : true, // check login status
         cookie : true, // enable cookies to allow the server to access the session
         xfbml  : true  // parse XFBML
       });
</script>

<div id="fba_itemlist">
	<div id="fbap_canvas_header">
		<h2>Metro Toronto Rotary TV Auction</h2>
		<p>November 18 &amp; 19 on <a href="http://www.rogerstv.com/rotarytvauction" target="_top">Rogers TV</a></p>
		<dl>
			<dt>BID LINE:</dt>
			<dd>(416) 406-6187</dd>
			<dt>INFO LINE:</dt>
			<dd>(416) 508-8382</dd>
		</dl>
		<div id="fbap_header">
			<a href="https://system.metrotorontorotaryauction.com/pdf/publiclist_2016.pdf" target="_top">Printable Item List</a></p>
		</div>
	</div>
<?php echo $this->layout()->content; ?>
</div>
</body>
</html>