<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The 38th Toronto Rotary Online Auction</title>

    <meta name="description" content="Annual online Rotary auction. Hundreds of great items, from Leafs and Raptors tickets to toys and electronics. Auction is held on eBay." />

    <!-- Twitter Card data -->
    <meta name="twitter:card" value="summary">

    <!-- Open Graph data -->
    <meta property="og:title" content="The 38th Toronto Rotary Online Auction" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="http://rotaryonline.auction/" />
    <meta property="og:image" content="http://rotaryonline.auction/img/auction_logo.png" />
    <meta property="og:description" content="Annual online Rotary auction. Hundreds of great items, from Leafs and Raptors tickets to toys and electronics. Auction is boardcast LIVE on YouTube, Facebook and Twitch." />

    <link rel="icon" sizes="192x192" href="/public/img/favicon_192x192.png">
    <link rel="shortcut icon" href="/public/img/favicon_64x64.ico">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#00246c">

    <!-- Bootstrap core CSS -->
    <link href="/public/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="/public/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- Custom styles for this template -->
    <link href="/public/css/landing-page.css" rel="stylesheet">
</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#"><img src="/public/img/auction_logo_small.png" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/public/index/index">Bid Board</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/public/index/items">Item List</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<section>

    <div class="container">
        <div class="row">
            <?php echo $this->layout()->content; ?>
        </div>

    </div>
    <!-- /.container -->
</section>

<!-- Footer -->
<footer>
    <div class="container">
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="#">Home</a>
            </li>
            <li class="footer-menu-divider list-inline-item">&sdot;</li>
            <li class="list-inline-item">
                <a href="http://rotary.org/" target="rotary">About Rotary</a>
            </li>
            <li class="footer-menu-divider list-inline-item">&sdot;</li>
            <li class="list-inline-item">
                <a href="mailto:info@rotaryonline.auction">Email Us</a>
            </li>
        </ul>
        <p class="copyright text-muted small">Copyright &copy; Toronto Area Rotary Clubs 2018. All Rights Reserved</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="/public/vendor/jquery/jquery.min.js"></script>
<script src="/public/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>