<div id="block_summary">
	<h3>Viewing Summary for Block #<?php echo $this->block->number; ?></h3>
	<table>
		<thead>
			<tr>
				<th>Item #</th>
				<th>Item Name</th>
				<th>Winner</th>
				<th>Value</th>
				<th>Bid</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->items as $item) { ?>
			<tr>
				<td><?php echo $item->itemNumber; ?></td>
				<td><?php echo $item->itemName;?></td>
				<td><?php echo $item->firstName . ' ' . $item->lastName; ?></td>
				<td><?php echo $item->itemValue; ?></td>
				<td><?php echo $item->bid; ?></td>
			</tr>
		<?php } ?>
		</tbody>
	</table>
</div>
